networks:
  march1_network:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3002"
    environment:
      - NODE_ENV=production
    container_name: march1-auth
    restart: unless-stopped
    env_file: ".env"
    networks:
      - march1_network
