on:
  pull_request:
    types: [opened, reopened]
name: test
jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey: |
            AUTH_JWT_SECRET=123456abcdef
          file_name: .env
      - name: Upload .env file
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env

  run-test:
    name: my-job
    runs-on: ubuntu-latest
    needs: create-envfile
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Download .env file
        uses: actions/download-artifact@v3
        with:
          name: env-file
          path: .

      - run: bun install
      - run: bun test
